apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 168370541191.dkr.ecr.us-west-1.amazonaws.com/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: gateway-config
          - secretRef:
              name: gateway-secret
