apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 168370541191.dkr.ecr.us-west-1.amazonaws.com/notification_service:latest
          envFrom:
          - configMapRef:
              name: notificationservice-config
          ports:
            - containerPort: 2342
