apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 168370541191.dkr.ecr.us-west-1.amazonaws.com/payment_service:latest
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secret
          # env:
          #   - name: SPRING_DATASOURCE_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: payment-service-config
          #         key: PAYMENT_SERVICE_DATASOURCE_URL
          #   - name: SPRING_DATASOURCE_USERNAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: payment-service-config
          #         key: PAYMENT_SERVICE_DATASOURCE_USERNAME
          #   - name: SPRING_DATASOURCE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: payment-service-secret
          #         key: PAYMENT_POSTGRES_PASSWORD
          #   - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          #     valueFrom:
          #       configMapKeyRef:
          #         name: common-config
          #         key: KAFKA_BOOTSTRAP_SERVERS
          ports:
            - containerPort: 8082
