version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kafka-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka-network

  userservice:
    build:
      context: ./src/Services/UserService/UserService.Api
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userservice;Username=postgres;Password=1234
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - kafka
      - postgres
    networks:
      - kafka-network

  eventservice:
    build:
      context: ./src/Services/EventService/EventService.Api
      dockerfile: Dockerfile
    container_name: eventservice
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data: