apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
type: Opaque
data:
  # ConnectionStrings__DefaultConnection: base64 encode if needed
  Jwt__Issuer: RXZlbnRUaWNrZXRQbGF0Zm9ybQ==
  JWT_ISSUER: RXZlbnRUaWNrZXRQbGF0Zm9ybQ==
  Jwt__Audience: RXZlbnRUaWNrZXRQbGF0Zm9ybS5BcGk=
  JWT_AUDIENCE: RXZlbnRUaWNrZXRQbGF0Zm9ybS5BcGk=
  Jwt__Key: Q0hBTkdFX01FX1RPX0FfTE9OR19SQU5ET01fMjU2X0JJVF9TRUNSRVQ=
  JWT_KEY: Q0hBTkdFX01FX1RPX0FfTE9OR19SQU5ET01fMjU2X0JJVF9TRUNSRVQ=
  Jwt__ExpiresMinutes: NjA=
  JWT_EXPIRES_MINUTES: NjA=
  POSTGRES_PASSWORD: MTIzNA==
