apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
type: Opaque
stringData:
  Jwt__Issuer: EventTicketPlatform
  Jwt__Audience: EventTicketPlatform.Api
  Jwt__Key: super-long-random-256-bit-secret-here-change-me
  Jwt__ExpiresMinutes: "60"
  POSTGRES_PASSWORD: "1234"
