apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  ORDER_POSTGRES_PASSWORD: MTIzNA==           # base64 of '1234'
  ORDER_SERVICE_DATASOURCE_PASSWORD: MTIzNA==
  POSTGRES_PASSWORD: MTIzNA==
