apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  # ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=userservice;Username=postgres;Password=1234"
  JWT_ISSUER: RXZlbnRUaWNrZXRQbGF0Zm9ybQ==
  Jwt__Audience: RXZlbnRUaWNrZXRQbGF0Zm9ybS5BcGk=
  JWT_AUDIENCE: RXZlbnRUaWNrZXRQbGF0Zm9ybS5BcGk=
  Jwt__Key: Q0hBTkdFX01FX1RPX0FfTE9OR19SQU5ET01fMjU2X0JJVF9TRUNSRVQ=
  JWT_KEY: Q0hBTkdFX01FX1RPX0FfTE9OR19SQU5ET01fMjU2X0JJVF9TRUNSRVQ=
  Jwt__ExpiresMinutes: NjA=
  JWT_EXPIRES_MINUTES: NjA=
  POSTGRES_PASSWORD: MTIzNA==
# stringData:
#   ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=userservice;Username=postgres;Password=1234
#   Jwt__Issuer: EventTicketPlatform
#   JWT_ISSUER: EventTicketPlatform
#   Jwt__Audience: EventTicketPlatform.Api
#   JWT_AUDIENCE: EventTicketPlatform.Api
#   Jwt__Key: CHANGE_ME_TO_A_LONG_RANDOM_256_BIT_SECRET
#   JWT_KEY: CHANGE_ME_TO_A_LONG_RANDOM_256_BIT_SECRET
#   Jwt__ExpiresMinutes: 60
#   JWT_EXPIRES_MINUTES: 60
#   POSTGRES_PASSWORD: 1234
