spring.application.name=ticket-service
server.port=8084
server.forward-headers-strategy=framework

# PostgreSQL DB connection (from env variables)
spring.datasource.url=${TICKET_SERVICE_DATASOURCE_URL}
spring.datasource.username=${TICKET_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${TICKET_SERVICE_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# spring.kafka.bootstrap-servers=${TICKET_SERVICE_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.bootstrap-servers=kafka:9092

# Producer (sending TicketReservedEvent)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer (receiving TicketReservedEvent)
spring.kafka.consumer.group-id=ticket-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted-packages=*

springdoc.api-docs.path=/swagger/v1/swagger.json
springdoc.swagger-ui.path=/swagger/index.html