apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  MongoDbSettings__ConnectionString: mongodb://mongo:27017
  MongoDbSettings__DatabaseName: EventServiceDb
  MongoDbSettings__EventsCollectionName: Events
  Kafka__BootstrapServers: kafka:9092
  POSTGRES_DB: eventservice
  POSTGRES_USER: postgres
