apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: payment-postgres
          image: postgres:15
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secret
          # env:
          #   - name: POSTGRES_DB
          #     valueFrom:
          #       configMapKeyRef:
          #         name: payment-service-config
          #         key: PAYMENT_POSTGRES_DB
          #   - name: POSTGRES_USER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: payment-service-config
          #         key: PAYMENT_SERVICE_DATASOURCE_USERNAME
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: payment-service-secret
          #         key: PAYMENT_POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: payment-pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: payment-pgdata
          emptyDir: {}
