spring.application.name=order_service
server.port=8083

spring.kafka.bootstrap-servers=${ORDER_SERVICE_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# PostgreSQL DB connection
spring.datasource.url=${ORDER_SERVICE_DATASOURCE_URL}
spring.datasource.username=${ORDER_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${ORDER_SERVICE_DATASOURCE_PASSWORD}

# JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------------------
# OpenAPI / Swagger (springdoc)
# Keep JSON at /swagger/v1/swagger.json (used by gateway at /orders/swagger/v1/swagger.json)
# Keep local Swagger UI at /swagger/index.html (optional)
# -------------------------------------
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger/index.html
springdoc.api-docs.path=/swagger/v1/swagger.json

# If you only want the gateway’s aggregated UI and not the service’s local UI, set:
# springdoc.swagger-ui.enabled=false

# Optional flag if your code reads it
swagger.use-gateway=true
