apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
# spec:
#   selector:
#     app: kafka
#   ports:
#     - name: broker
#       protocol: TCP
#       port: 9092
#       targetPort: 9092
#     - name: external
#       protocol: TCP
#       port: 29092
#       targetPort: 29092
#   type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka
# spec:
#   selector:
#     app: kafka
#   ports:
#     - protocol: TCP
#       port: 9092
#       targetPort: 9092
#   type: ClusterIP
