apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        # Broker talks to ZooKeeper
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        # Plaintext for dev
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        # Kafka clients inside the cluster can reach it via the Service DNS
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # Convenience for demos/dev
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
      volumes:
      - name: data
        emptyDir: {}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: confluentinc/cp-kafka:7.3.0
#         ports:
#         - name: broker
#           containerPort: 9092
#         - name: external
#           containerPort: 29092
#         env:
#         - name: KAFKA_BROKER_ID
#           value: "1"
#         - name: KAFKA_ZOOKEEPER_CONNECT
#           value: zookeeper:2181
#         - name: KAFKA_LISTENERS
#           value: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
#         - name: KAFKA_ADVERTISED_LISTENERS
#           value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
#         - name: KAFKA_INTER_BROKER_LISTENER_NAME
#           value: PLAINTEXT
#         - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#           value: "1"
#         readinessProbe:
#           tcpSocket:
#             port: 9092
#           initialDelaySeconds: 60
#           periodSeconds: 10
#         livenessProbe:
#           tcpSocket:
#             port: 9092
#           initialDelaySeconds: 60
#           periodSeconds: 10

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       initContainers:
#         - name: wait-for-zookeeper
#           image: busybox:1.35
#           command: ['sh', '-c', 'until nc -z zookeeper 2181; do echo waiting for zookeeper; sleep 5; done;']
#       containers:
#         - name: kafka
#           image: confluentinc/cp-kafka:7.3.0
#           ports:
#             - containerPort: 9092
#           env:
#             - name: KAFKA_BROKER_ID
#               value: "1"
#             - name: KAFKA_ZOOKEEPER_CONNECT
#               value: zookeeper:2181
#             - name: KAFKA_LISTENERS
#               value: PLAINTEXT://0.0.0.0:9092
#             - name: KAFKA_ADVERTISED_LISTENERS
#               value: PLAINTEXT://kafka:9092
#             - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#               value: "1"