apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_4LW_COMMANDS_WHITELIST
          value: "ruok,stat,srvr"
        readinessProbe:
          exec:
            command: ["/bin/sh","-c","echo ruok | nc 127.0.0.1 2181 | grep imok"]
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["/bin/sh","-c","echo srvr | nc 127.0.0.1 2181 | grep Mode"]
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /bitnami/zookeeper
      volumes:
      - name: data
        emptyDir: {}
